---

- name: Provisioning {{ project_name }}
  hosts: {{ hosts }}
  sudo: {{ sudo }}
  vars_files:
    - vars/main.yml
{% for role in vars_files %}
    - vars/{{ role }}.yml
{% endfor %}

  roles:
{% for role in selected_roles %}
{% if role != 'ubuntu-xdebug' %}
    - {{ role }}
{% endif %}
{% endfor %}

{% if 'ubuntu-xdebug' in selected_roles %}
- name: Vagrant provisioning
  hosts: vagrant
  sudo: yes
  gather_facts: true
  roles:
   - ubuntu-xdebug
{% endif %}
