---

- name: Provisioning {{ project_name }}
  hosts: {{ hosts }}
  sudo: {{ sudo }}
  vars_files:
    - vars/main.yml
{% for service in vars_files %}
    - vars/{{ service }}.yml
{% endfor %}

  roles:
{% for service in selected_services %}
{% if service != 'ubuntu-xdebug' %}
    - {{ service }}
{% endif %}
{% endfor %}

{% if 'ubuntu-xdebug' in selected_services %}
- name: Vagrant provisioning
  hosts: vagrant
  sudo: yes
  gather_facts: true
  roles:
   - ubuntu-xdebug
{% endif %}
