project_type: "nodejs"
project_name: test-fansible
timezone: "Europe/Paris"
port: 80
hosts: all
sudo: "true"
apt_install: []

roles:
  - ubuntu-apt
  - create-www-data-user
  - nodejs
  - ubuntu-nodejs-nginx
