project_name: test-fansible
timezone: "Europe/Paris"
port: 80
hosts: all
sudo: "true"

services:
  - apt
  - create-www-data-user
  - nodejs
  - nodejs-nginx

vagrant:
  ip: 10.0.0.10
  box: "ubuntu/trusty64"
  memory: 1024
  cpus: 1
  exec: 100
  src: .
