project_type: "laravel"
project_name: test-fansible
timezone: "Europe/Paris"
port: 80
hosts: all
sudo: "true"
apt_install: []

roles:
  - ubuntu-apt
  - create-www-data-user
  - ubuntu-php
  - composer
  - ubuntu-laravel-nginx
  - ubuntu-xdebug

vagrant:
  ip: 10.0.0.10
  box: "ubuntu/trusty64"
  memory: 1024
  cpus: 1
  exec: 100
  src: .

database_name: 'homestead'
database_user: 'homestead'
database_password: 'secret'
