project_type: "laravel"
project_name: test-fansible
timezone: "Europe/Paris"
port: 80
hosts: all
sudo: "true"
apt_install: []

roles:
  - ubuntu-apt
  - create-www-data-user
  - ubuntu-php
  - composer
  - ubuntu-laravel-nginx
  - ubuntu-xdebug

database_name: 'homestead'
database_user: 'homestead'
database_password: 'secret'
