---

apache_repository: false

apache_site_enable:
  - "{{ inventory_hostname }}"

apache_vhosts:
  - servername: "{{ inventory_hostname }}"
    index: app.php
    port: {{ port }}
    documentroot: "/var/www/{{ project_name }}/current/web"
    directory_extra:
      - "RewriteEngine On"
      - "RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\\2$"
      - "RewriteRule ^(.*) - [E=BASE:%1]"
      - "RewriteCond %{ENV:REDIRECT_STATUS} ^$"
      - "RewriteRule ^app\\.php(/(.*)|$) %{ENV:BASE}/$2 [R=301,L]"
      - "RewriteCond %{REQUEST_FILENAME} -f"
      - "RewriteRule .? - [L]"
      - "RewriteRule .? %{ENV:BASE}/app.php [L]"
