---
#PUT here your main variable
project_name: {{ project_name }}
port: {{ port }}
apt_specific_packages:
  - git

{% for role in roles %}
{% if role == 'ubuntu-symfony-nginx' %}
composer_update: false
{% endif %}
{% if role == 'ubuntu-postgresql' %}
postgresql_version: 9.6
{% endif %}
{% endfor %}
